#!/usr/bin/env python3
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / '.env'
EXAMPLE_PATH = ROOT / '.env.example'


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        raise SystemExit(f'ERROR: {path} not found. Copy .env.example to .env first.')
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def write_miniprogram_config(env: dict[str, str]) -> None:
    content = f"""module.exports = {{
  API_BASE_URL: {js_string(env.get('MINIPROGRAM_API_BASE_URL', 'http://127.0.0.1:17800'))},
  OSS: {{
    BUCKET: {js_string(env.get('OSS_BUCKET', ''))},
    ENDPOINT: {js_string(env.get('OSS_ENDPOINT', ''))},
    PREFIX: {js_string(env.get('OSS_PREFIX', ''))},
    ACCESS_KEY_ID: {js_string(env.get('OSS_ACCESS_KEY_ID', ''))},
    ACCESS_KEY_SECRET: {js_string(env.get('OSS_ACCESS_KEY_SECRET', ''))},
  }},
}}
"""
    (ROOT / 'config.local.js').write_text(content, encoding='utf-8')


def write_server_env(env: dict[str, str]) -> None:
    keys = [
        'MINIPROGRAM_API_BASE_URL',
        'OSS_BUCKET',
        'OSS_ENDPOINT',
        'OSS_PREFIX',
        'SERVER_HOST',
        'SERVER_PORT',
        'SERVER_DB_PATH',
        'SERVER_IMPORT_XLSX',
        'SERVER_EXPORT_XLSX',
        'SERVER_UPDATE_XLSX',
    ]
    lines = [f'{key}={env.get(key, "")}' for key in keys if key in env]
    server_env = ROOT / 'server' / '.env'
    server_env.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def write_project_private_config(env: dict[str, str]) -> None:
    appid = env.get('WECHAT_APPID', '').strip()
    if not appid or appid == 'your-wechat-appid':
        return
    path = ROOT / 'project.private.config.json'
    data = {}
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding='utf-8'))
        except json.JSONDecodeError:
            data = {}
    data['appid'] = appid
    data.setdefault('description', 'Local private config generated by scripts/setup_config.py')
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


def main() -> None:
    if not ENV_PATH.exists() and EXAMPLE_PATH.exists():
        raise SystemExit('ERROR: .env not found. Run: cp .env.example .env')
    env = read_env(ENV_PATH)
    write_miniprogram_config(env)
    write_server_env(env)
    write_project_private_config(env)
    print('Generated config.local.js and server/.env')
    if env.get('WECHAT_APPID') and env.get('WECHAT_APPID') != 'your-wechat-appid':
        print('Updated project.private.config.json')


if __name__ == '__main__':
    main()
